server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: codeInterview
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      strategy: first
      http-response-body: "{ \"type\": \"ERROR\", \"response\": { \"message\": \"Too Many Requests\"}}"
      rate-limits:
        - cache-key: "'default'"  # "getHeader('X-api-key')"
          bandwidths:
            - capacity: 1
              time: 1
              unit: seconds
            - capacity: 5
              time: 1
              unit: minutes
            - capacity: 100
              time: 1
              unit: hours


logging:
  level:
    com.meet.time.interview: debug

application:
  hubspot-app:
    base-url: ${HUBSPOT_BASE_URL}
    base-oauth-url: ${HUBSPOT_OAUTH_AUTHENTICATE_BASE_URL}
    client-id: ${HUBSPOT_CLIENT_ID}
    client-app: ${HUBSPOT_CLIENT_APP}
    client-secret: ${HUBSPOT_SECRET_KEYS}
    authorization-endpoint: ${HUBSPOT_AUTHORIZATION_ENDPOINT}
    contact-endpoint: ${HUBSPOT_CONTACT_ENDPOINT}
    access-token-endpoint: ${HUBSPOT_ACCESS_TOKEN_ENDPOINT}
    redirect-uri: ${HUBSPOT_REDIRECT_URI}
