server:
  port: ${SERVER_PORT}

spring:
  application:
    name: codeInterview

logging:
  level:
    com.meet.time.interview: debug

application:
  hubspot-app:
    client-id: ${HUBSPOT_CLIENT_ID}
    client-app: ${HUBSPOT_CLIENT_APP}
    client-secret: ${HUBSPOT_SECRET_KEYS}
    authorization-url: ${HUBSPOT_AUTHORIZATION_URL}